name: CI Pipeline Python

on: [push] # Seejecuta al hacer push

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout del codigo
              uses: actions/checkout@v4

            - name: Configurar Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"

            - name: Ejecutar Script
              run: python script.py

            - name: Subir resultado como artefacto
              uses: actions/upload-artifact@v4
              with:
                  name: resultado-ejecucion
                  path: resultado.txt

            - name: Notificar exito
              if: success()
              run: echo "Pipeline completado! Ver artefacto en Summary"